In [8]:
import numpy as np


In [19]:
def calculate(array):
  if len(array) != 9:
    raise ValueError("List must contain nine numbers.")

  a = np.array(array).reshape(3, 3)
  print(a)
  cal = dict()
  cal["mean"] = (a.mean(axis=0).tolist(), a.mean(axis=1).tolist(), a.mean())
  cal["variance"] = (a.var(axis=0).tolist(), a.var(axis=1).tolist(), a.var())
  cal["standard deviation"] = (a.std(axis=0).tolist(), a.std(axis=1).tolist(), a.std())
  cal["max"] = (a.max(axis=0).tolist(), a.max(axis=1).tolist(), a.max())
  cal["min"] = (a.min(axis=0).tolist(), a.min(axis=1).tolist(), a.min())
  cal["sum"] = (a.sum(axis=0).tolist(), a.sum(axis=1).tolist(), a.sum())

  return cal


In [20]:
calculate(([0,1,2,3,4,5,6,7,8]))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


{'mean': ([3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0),
 'variance': ([6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667),
 'standard deviation': ([2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611),
 'max': ([6, 7, 8], [2, 5, 8], 8),
 'min': ([0, 1, 2], [0, 3, 6], 0),
 'sum': ([9, 12, 15], [3, 12, 21], 36)}